### ISSUE TITLE
Compiling code from source fails

### ISSUE THREAD

**Issue by ms-mtbkr** [palmerr23/SwissArmyKnife#1]
Hi Richard,
  Beautiful project. I have two boards with all of the surface mount components, and DIL connectors installed. Ready for a few basic tests, but I can't get the first version of the software to build. I have a working Arduino environment newly installed, and have imported the '.zip' SwissArmy project directory. It looks like this is an earlier version before going to an OTA version? There appear to be filename differences, eg SwissArmy.ino has '#include "mySCPI_relay.h"' where the filename is 'mySCPI_Relay.h'. Also, the list of libraries that need to be installed has to be updated, eg "MCP45HVX1" and others. Could you have a look please? Also, is there any project discussion around this? You might curate a thread on EEVBlog.
Regards, 
Mike

**Comment by palmerr23** [comment]
Mike,

Firstly, what OS are you building on - case sensitive file names indicates Linux? The original was built on Windows - sorry for the laxity on filename case.

I'll :
- check the version of the code files - as they may be out of date 
- tidy up the case on the include file names
- update the list of libraries and add any that aren't easily available.

I'll post again after I've done these things.

Have you tried the files in the download link supplied in the Silicon Chip article?

As for OTA, that's independent of the code - simply another way to upload a .bin file to the ESP32.

Also, if you have Arduino 2.0 installed, you'll need a utility to upload the data files, as this is only available (so far) in Arduino 1.x.  

If you don't have access to something else, my OTA + file manager utility is at https://github.com/palmerr23/ESP32-OTA-and-File-Manager

**Comment by ms-mtbkr** [comment]
Thanks for your prompt  reply. Yes, I am running Linux, and a 2.0 series Arduino. I did try files from the Silicon Chip website, but the code looks the same. Also,  I have been playing with the file names, and installing libraries. After fixing the obvious, I tried installing ESPASyncWebSrv by dvarrel (a guess),  I think the code includes ESPASyncWebServer.h. Then I got "mySHTML_processor.h:147:202: error: 'FMAX' was not declared in this scope". When you do a revision, I'll try again from a clean build.
  This is an extraordinary design, and I think it will be very popular, which unfortunately also means some teething issues.

**Comment by palmerr23** [comment]
The ESPASyncWebSrv library I used is by me-no-dev
 
https://github.com/me-no-dev/ESPAsyncWebServer

and also requires 

https://github.com/me-no-dev/AsyncTCP

Also see the other issue - there's a fault in the PCBs

**Comment by palmerr23** [comment]
I've updated 
* case of the include files in the .ino file
* list of required libraries

I've also compared the files here with my off-line source and they are up to date.

**Comment by ms-mtbkr** [comment]
Thank you, I'll give it a go. I'm a github newbie - unsure of the protocols : I close the issue?

I'll look at the PCB issue in a minute. So many questions! KiCAD or something else? Did you put it through assembly?  But, I'm sure you are very busy with this thing now.
Regards,
Mike

**Comment by palmerr23** [comment]
I'll close the issue once you've confirmed it works.
