### ISSUE TITLE
PCB fault

### ISSUE THREAD

**Issue by palmerr23** [palmerr23/SwissArmyKnife#2]
ESP32 pins 20-38 are reversed on the PCB.

I will publish a hardware/software fix as soon as I have it

**Comment by ms-mtbkr** [comment]
Hi again!
  So :- now may I ask what PCB design package you used? Doesn't SC use Altium?
  Do you intend to  publish any version of the PCB design files? 

  How can I help with the project? 

  The hand assembly is reasonably difficult, but the project would appeal across the board to anyone interested in analog - ie *real* beginners. But there lies the rub - you need more than beginner skills to build it. My vote is KiCAD, and let the robots do most of the build. Where do you want to take this?

  BTW, I'm new to ESP32 also. If I have to hand-make a harness, that shouldn't be too difficult. But then, I should go directly to my favorite CPU ...  also,
- bigger pads if you want it to be only a hand soldered work of art, 
- especially for the yummy miniMELFs (JLCPCB Basic component, as are all of the passives)
- The 5V to +/-15V converter looks like a gem.

**Comment by palmerr23** [comment]
Hi,

I'm a KiCAD user, and yes SC uses Altium.

No, SC has the exclusive use of the design files - as the proceeds of their online shop help keep the magazine afloat.

I have the fix in hand, I just want to test it before publishing the solution - part rewiring and part software for the affected pins.

**Comment by ms-mtbkr** [comment]
So to clarify, the pin reversal affects one side of the package ... no power supply pins, so having plugged the CPU into it's socket, probably no harm done. 
  I'm also using KiCAD.

**Comment by palmerr23** [comment]
The CLK pin will have been be grounded when plugged in, which is unlikely to cause damage. 

If the ESP still boots when unplugged, then everything's probably OK.

**Comment by palmerr23** [comment]
Instructions for correcting the faults on Rev A boards are included on the main page for this project.
